"""pyml-workbench: tabular and sequence ML with validation search and durable queues."""
from .adapters import EstimatorAdapter, UnsupportedOperationError
from .catalog import (
    ModelNotAvailableError,
    build_estimator,
    get_model,
    list_models,
    model_capabilities,
)
from .config import ConfigError, DatasetConfig, ExperimentConfig, SplitConfig
from .batch import (
    BatchError,
    create_search_job,
    create_search_jobs,
    export_training_exploration,
    finalize_frozen_search,
    freeze_search_winner,
    get_job_summary,
    load_search_result,
    request_job_control,
    run_batch,
    run_pending_search_jobs,
    run_search_job,
    run_search_jobs,
)
from .data import DatasetError, DatasetPreview, LoadedDataset, MissingTargetError, load_dataset, preview_dataset
from .experiment import (
    ArtifactError,
    ExperimentError,
    ExperimentResult,
    ExperimentSession,
    FittedModel,
    SplitError,
    finalize_experiment,
    freeze_experiment,
    evaluate_test,
    load_model,
    prepare_experiment,
    predict,
    run_experiment,
    transform,
)
from .history import BudgetExhausted, DispatchStopped, HistoryError, HistoryStore
from .objectives import ObjectiveSpec
from .parameters import parameter_schema
from .search import SearchResult, SearchSpec, TrialRecord
from .search_space import SearchSpace, recommended_space
from .sequence import SequenceConfig, SequenceError, SequencePlan
from .selection import FinalSelection, FrozenSelection

__version__ = "0.4.4"

__all__ = [
    "BatchError",
    "BudgetExhausted",
    "ConfigError",
    "ArtifactError",
    "DatasetConfig",
    "DatasetError",
    "DatasetPreview",
    "ExperimentError",
    "ExperimentResult",
    "ExperimentSession",
    "FinalSelection",
    "FrozenSelection",
    "FittedModel",
    "EstimatorAdapter",
    "ExperimentConfig",
    "LoadedDataset",
    "HistoryError",
    "HistoryStore",
    "MissingTargetError",
    "ModelNotAvailableError",
    "SplitError",
    "SplitConfig",
    "SearchResult",
    "SearchSpace",
    "SearchSpec",
    "SequenceConfig",
    "SequenceError",
    "SequencePlan",
    "ObjectiveSpec",
    "DispatchStopped",
    "TrialRecord",
    "UnsupportedOperationError",
    "build_estimator",
    "create_search_job",
    "create_search_jobs",
    "export_training_exploration",
    "get_model",
    "get_job_summary",
    "finalize_frozen_search",
    "finalize_experiment",
    "freeze_search_winner",
    "freeze_experiment",
    "evaluate_test",
    "load_dataset",
    "load_search_result",
    "load_model",
    "list_models",
    "model_capabilities",
    "parameter_schema",
    "predict",
    "prepare_experiment",
    "preview_dataset",
    "request_job_control",
    "run_batch",
    "run_pending_search_jobs",
    "run_search_job",
    "run_search_jobs",
    "recommended_space",
    "run_experiment",
    "transform",
    "__version__",
]
